"""Generates a tool reference from real Tool instances - never hand-edited,
regenerated by scripts/generate_docs.py and checked for staleness by
tests/test_docgen_freshness.py.
"""

HEADER = "# Tools\n\nGenerated from the real tool registry - do not hand-edit; run `python3 scripts/generate_docs.py` instead.\n"


def generate_tools_doc(tools):
    """`tools` is a real list of Tool instances (e.g. tool_registry.list()),
    injected rather than imported - this module never needs to know about
    tools.registry specifically."""
    lines = [HEADER]
    for tool in sorted(tools, key=lambda t: t.name):
        lines.append(f"\n## `{tool.name}`\n")
        lines.append(f"{tool.description}\n")
        lines.append(f"- Permission: `{tool.permission}`")
        if tool.parameters:
            lines.append("- Parameters:")
            for name, description in tool.parameters.items():
                lines.append(f"  - `{name}`: {description}")
    return "\n".join(lines) + "\n"
